# Generated by Django 5.2.8 on 2025-11-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_stripe_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('contrareembolso', 'Contrareembolso')], max_length=30),
        ),
    ]
