# Generated by Django 5.2.8 on 2025-11-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_tracking_token_and_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_entrega',
            field=models.CharField(choices=[('estandar', 'Envío estándar (48-72h)'), ('urgente', 'Envío urgente (24h)'), ('recogida', 'Recogida en tienda')], default='estandar', max_length=20),
        ),
    ]
