# Generated by Django 5.2.8 on 2025-11-06 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TallaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("talla", models.CharField(max_length=10)),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tallas",
                        to="productos.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Talla de producto",
                "verbose_name_plural": "Tallas de productos",
            },
        ),
    ]
