# Generated by Django 5.2.8 on 2025-11-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_populate_navigation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='imagenproducto',
            constraint=models.UniqueConstraint(fields=('producto',), name='unique_imagen_por_producto'),
        ),
    ]
